export type RltState =
  | "SUBMITTED"
  | "TERMINOLOGY_RESOLVED"
  | "FHIR_REQUEST_CREATED"
  | "SENT_TO_MOLIS"
  | "ORDER_RECEIVED"
  | "RESULT_AVAILABLE"
  | "RESULT_MAPPED"
  | "COMPLETED"
  | "FAILED";